[build]
  # The base directory must be lowercase
  base = "frontend"

  # The build command is correct
  command = "npm run build"

  # The publish directory should be 'dist' (relative to the base)
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"